services:
  dash-app:
    build: .            
    image: kdash   # Ahora esto servirá como etiqueta local
    container_name: kdash_cont
    ports:
      - "8052:8052"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    networks:
      - shared_network

networks:
  shared_network:
    external: true